name: portifolio
description: "Portifolio Matheus Lula"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.14
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_lula.png"
  adaptive_icon_background: "#080322"
  adaptive_icon_foreground: "assets/images/logo_lula.png"
  name: "Portifolio"

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/barcolor.png
    - assets/images/fundo.jpg
    - assets/images/perfil_port.png
    - assets/images/logo_lula.png
    - assets/images/logo_lula.svg
    - assets/tecno/email.png
    - assets/tecno/insta.png
    - assets/tecno/flutter.png
    - assets/tecno/github.png
    - assets/tecno/kotlin.png
    - assets/tecno/linkedin.png
    - assets/tecno/react.png
    - assets/tecno/firebase.png
    - assets/tecno/js.png
    - assets/tecno/mongo.png
    - assets/tecno/postg.png
    - assets/tecno/python.png
    - assets/tecno/ts.png
    - assets/projeto/deltacomerce.png
    - assets/projeto/indisponivel.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: JockeyOne
      fonts:
        - asset: assets/fonts/JockeyOne-Regular.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
