name: portifolio
description: "Portifolio Matheus Lula"

publish_to: 'none' # Remova esta linha se for publicar no pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.14
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/barcolor.webp
    - assets/images/perfil_port.webp
    - assets/images/logo_lula.webp
    - assets/tecno/email.webp
    - assets/tecno/insta.webp
    - assets/tecno/flutter.webp
    - assets/tecno/github.webp
    - assets/tecno/kotlin.webp
    - assets/tecno/linkedin.webp
    - assets/tecno/react.webp
    - assets/tecno/firebase.webp
    - assets/tecno/js.webp
    - assets/tecno/mongo.webp
    - assets/tecno/postg.webp
    - assets/tecno/python.webp
    - assets/tecno/ts.webp
    - assets/projeto/deltacomerce.webp
    - assets/projeto/indisponivel.webp

  fonts:
    - family: JockeyOne
      fonts:
        - asset: assets/fonts/JockeyOne-Regular.ttf