name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'

      - name: Instalar dependências
        run: flutter pub get

      - name: Construir versão web
        run: flutter build web --release

      - name: Deploy para GitHub Pages
        uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /portifolio/
          github_token: ${{ secrets.GITHUB_TOKEN }}
