name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Garante que a Action pode escrever no repositório

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'  # Use a versão correta do Flutter

      - name: Ativar suporte para Web no Flutter
        run: flutter config --enable-web

      - name: Instalar dependências do Flutter
        run: flutter pub get

      - name: Construir versão Web
        run: flutter build web --release

      - name: Deploy para GitHub Pages
        uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /portifolio/
          targetBranch: gh-pages
